### ISSUE TITLE
emberfire 1.2.6-1.3 does not work with ember 1.8+

### ISSUE THREAD

**Issue by codepreneur** [firebase/emberfire#156]
When I try to use it, it doesn't save (breaks when I try to do `.save()` and I get all sorts of errors, for example:
```
Uncaught TypeError: undefined is not a function vendor.js:30274(anonymous function) vendor.js:30274Cache.get vendor.js:25100isPath vendor.js:30296get vendor.js:31065__exports__.default.Ember.Object.extend.serializeAttribute vendor.js:73899(anonymous function) vendor.js:73830(anonymous function) vendor.js:76059cb vendor.js:29082OrderedSet.forEach vendor.js:28880Map.forEach vendor.js:29090Model.reopenClass.eachAttribute vendor.js:76058Model.reopen.eachAttribute vendor.js:76115__exports__.default.Ember.Object.extend.serialize vendor.js:73829Ember.Object.extend.serialize vendor.js:80508Ember.Object.extend.serialize vendor.js:76925DS.FirebaseAdapter.DS.Adapter.extend.updateRecord vendor.js:83726DS.FirebaseAdapter.DS.Adapter.extend.createRecord vendor.js:83703_commit vendor.js:82163(anonymous function) vendor.js:81386forEach vendor.js:27206Ember.Object.extend.flushPendingSave vendor.js:81371DeferredActionQueues.invoke vendor.js:13853DeferredActionQueues.flush vendor.js:13923Backburner.end vendor.js:13309Backburner.run vendor.js:13364run vendor.js:31397handleRegisteredAction vendor.js:33338(anonymous function) vendor.js:51898jQuery.event.dispatch vendor.js:4759elemData.handle vendor.js:4427
```
![image](https://cloud.githubusercontent.com/assets/3421858/4980448/36f40e40-6900-11e4-835f-cf85b2f29528.png)

and if I click on vendor.js I get:
```
var isPathCache       = new Cache(1000, function(key) { return key.indexOf('.')      !== -1; })
```
![image](https://cloud.githubusercontent.com/assets/3421858/4980381/c938a000-68ff-11e4-81d9-e95c7ac92994.png)

emberfire 1.3+ works fine with ember 1.7 though.

**Comment by sararob** [comment]
@codepreneur @20v100 this is fixed with the latest release (1.3.2). Are you still having issues?

**Comment by 20v100** [comment]
@sararob I changed my code since then. I could not re-create the issue. I consider the bug as fixed. Thanks

**Comment by codepreneur** [comment]
It works now, even with latest and greatest:
```
version: 0.1.9 (ember-cli)
node: 0.10.35
npm: 2.1.8
```

```
 "dependencies": {
    "handlebars": "~2.0.0",
    "jquery": "2.1.3",
    "ember": "1.10.0-beta.4",
    "ember-data": "1.0.0-beta.12",
    "emberfire": "~1.3.2"
}
```
